/*
 * rcc_clock_defs.h
 *
 * Contains clock enable/disable definitions.
 */

#ifndef INC_RCC_CLOCK_DEFS_H_
#define INC_RCC_CLOCK_DEFS_H_

#include "mcu.h"

/* Clock Enable Definitions */
// Here you define macros to enable clocks for various peripherals
// GPIOs
#define RCC_GPIOA_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN))
#define RCC_GPIOB_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOBEN))
#define RCC_GPIOC_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOCEN))
#define RCC_GPIOD_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIODEN))
#define RCC_GPIOE_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOEEN))
#define RCC_GPIOF_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOFEN))
#define RCC_GPIOG_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOGEN))
#define RCC_GPIOH_CLK_ENABLE()		(RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOHEN))

// SYSCFG
#define RCC_SYSCFG_CLK_ENABLE()   (RCC->APB2ENR |= (RCC_APB2ENR_SYSCFGEN))

// DMA
#define RCC_DMA1_CLK_ENABLE()     (RCC->AHB1ENR |= (RCC_AHB1ENR_DMA1EN))
#define RCC_DMA2_CLK_ENABLE()     (RCC->AHB1ENR |= (RCC_AHB1ENR_DMA2EN))

// ADC
#define RCC_ADC1_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_ADC1EN))
#define RCC_ADC2_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_ADC2EN))
#define RCC_ADC3_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_ADC3EN))

// SPI
#define RCC_SPI1_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_SPI1EN))
#define RCC_SPI2_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_SPI2EN))
#define RCC_SPI3_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_SPI3EN))
#define RCC_SPI4_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_SPI4EN))

// I2C
#define RCC_I2C1_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_I2C1EN))
#define RCC_I2C2_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_I2C2EN))
#define RCC_I2C3_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_I2C3EN))

// TIM
#define RCC_TIM1_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_TIM1EN))
#define RCC_TIM2_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_TIM2EN))
#define RCC_TIM3_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_TIM3EN))
#define RCC_TIM4_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_TIM4EN))
#define RCC_TIM5_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_TIM5EN))
#define RCC_TIM6_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_TIM6EN))
#define RCC_TIM7_CLK_ENABLE()     (RCC->APB1ENR |= (RCC_APB1ENR_TIM7EN))
#define RCC_TIM8_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_TIM8EN))
#define RCC_TIM9_CLK_ENABLE()     (RCC->APB2ENR |= (RCC_APB2ENR_TIM9EN))
#define RCC_TIM10_CLK_ENABLE()    (RCC->APB2ENR |= (RCC_APB2ENR_TIM10EN))
#define RCC_TIM11_CLK_ENABLE()    (RCC->APB2ENR |= (RCC_APB2ENR_TIM11EN))
#define RCC_TIM12_CLK_ENABLE()    (RCC->APB1ENR |= (RCC_APB1ENR_TIM12EN))
#define RCC_TIM13_CLK_ENABLE()    (RCC->APB1ENR |= (RCC_APB1ENR_TIM13EN))
#define RCC_TIM14_CLK_ENABLE()    (RCC->APB1ENR |= (RCC_APB1ENR_TIM14EN))

// USART
#define RCC_USART1_CLK_ENABLE()   (RCC->APB2ENR |= (RCC_APB2ENR_USART1EN))
#define RCC_USART2_CLK_ENABLE()   (RCC->APB1ENR |= (RCC_APB1ENR_USART2EN))
#define RCC_USART3_CLK_ENABLE()   (RCC->APB1ENR |= (RCC_APB1ENR_USART3EN))
#define RCC_UART4_CLK_ENABLE()    (RCC->APB1ENR |= (RCC_APB1ENR_UART4EN))
#define RCC_UART5_CLK_ENABLE()    (RCC->APB1ENR |= (RCC_APB1ENR_UART5EN))
#define RCC_USART6_CLK_ENABLE()   (RCC->APB2ENR |= (RCC_APB2ENR_USART6EN))

// --------------------------------------------------
/* Clock Disable Definitions */
// Here you define macros to disable clocks for various peripherals
// GPIOs
#define RCC_GPIOA_CLK_DISABLE()   (RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOAEN))
#define RCC_GPIOB_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOBEN))
#define RCC_GPIOC_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOCEN))
#define RCC_GPIOD_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIODEN))
#define RCC_GPIOE_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOEEN))
#define RCC_GPIOF_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOFEN))
#define RCC_GPIOG_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOGEN))
#define RCC_GPIOH_CLK_DISABLE()		(RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOHEN))

// SYSCFG
#define RCC_SYSCFG_CLK_DISABLE()  (RCC->APB2ENR &= ~(RCC_APB2ENR_SYSCFGEN))

// ADC
#define RCC_ADC1_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_ADC1EN))
#define RCC_ADC2_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_ADC2EN))
#define RCC_ADC3_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_ADC3EN))

// DMA
#define RCC_DMA1_CLK_DISABLE()    (RCC->AHB1ENR &= ~(RCC_AHB1ENR_DMA1EN))
#define RCC_DMA2_CLK_DISABLE()    (RCC->AHB1ENR &= ~(RCC_AHB1ENR_DMA2EN))

// SPI
#define RCC_SPI1_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_SPI1EN))
#define RCC_SPI2_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_SPI2EN))
#define RCC_SPI3_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_SPI3EN))
#define RCC_SPI4_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_SPI4EN))

// I2C
#define RCC_I2C1_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_I2C1EN))
#define RCC_I2C2_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_I2C2EN))
#define RCC_I2C3_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_I2C3EN))

// TIM
#define RCC_TIM1_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_TIM1EN))
#define RCC_TIM2_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM2EN))
#define RCC_TIM3_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM3EN))
#define RCC_TIM4_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM4EN))
#define RCC_TIM5_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM5EN))
#define RCC_TIM6_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM6EN))
#define RCC_TIM7_CLK_DISABLE()    (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM7EN))
#define RCC_TIM8_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_TIM8EN))
#define RCC_TIM9_CLK_DISABLE()    (RCC->APB2ENR &= ~(RCC_APB2ENR_TIM9EN))
#define RCC_TIM10_CLK_DISABLE()   (RCC->APB2ENR &= ~(RCC_APB2ENR_TIM10EN))
#define RCC_TIM11_CLK_DISABLE()   (RCC->APB2ENR &= ~(RCC_APB2ENR_TIM11EN))
#define RCC_TIM12_CLK_DISABLE()   (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM12EN))
#define RCC_TIM13_CLK_DISABLE()   (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM13EN))
#define RCC_TIM14_CLK_DISABLE()   (RCC->APB1ENR &= ~(RCC_APB1ENR_TIM14EN))

// USART
#define RCC_USART1_CLK_DISABLE()  (RCC->APB2ENR &= ~(RCC_APB2ENR_USART1EN))
#define RCC_USART2_CLK_DISABLE()  (RCC->APB2ENR &= ~(RCC_APB1ENR_USART2EN))
#define RCC_USART3_CLK_DISABLE()  (RCC->APB2ENR &= ~(RCC_APB1ENR_USART3EN))
#define RCC_UART4_CLK_DISABLE()   (RCC->APB2ENR &= ~(RCC_APB1ENR_UART4EN))
#define RCC_UART5_CLK_DISABLE()   (RCC->APB2ENR &= ~(RCC_APB1ENR_UART5EN))
#define RCC_USART6_CLK_DISABLE()  (RCC->APB2ENR &= ~(RCC_APB2ENR_USART6EN))

#endif /* INC_RCC_CLOCK_DEFS_H_ */
